import type { PersistedState } from '../types/taxonomy';

export const SEED_STATE: PersistedState = {
  typeVocabulary: [
    { id: 'domain',  label: 'Domain',  color: 'purple', isDefault: true },
    { id: 'topic',   label: 'Topic',   color: 'teal',   isDefault: true },
    { id: 'concept', label: 'Concept', color: 'blue',   isDefault: true },
    { id: 'skill',   label: 'Skill',   color: 'amber',  isDefault: true },
    { id: 'example', label: 'Example', color: 'coral',  isDefault: true },
  ],
  rootIds: ['domain-1'],
  nodes: {
    'domain-1': {
      id: 'domain-1',
      label: 'Data Literacy',
      description: 'The ability to read, understand, create, and communicate data as information.',
      type: 'domain',
      parentId: null,
      childIds: ['topic-1', 'topic-2', 'topic-3'],
      createdAt: 1700000000000,
      updatedAt: 1700000000000,
    },
    'topic-1': {
      id: 'topic-1',
      label: 'Data Collection',
      description: 'Methods and practices for gathering raw data.',
      type: 'topic',
      parentId: 'domain-1',
      childIds: ['concept-1', 'concept-2'],
      createdAt: 1700000001000,
      updatedAt: 1700000001000,
    },
    'topic-2': {
      id: 'topic-2',
      label: 'Data Analysis',
      description: 'Techniques for examining data to draw conclusions.',
      type: 'topic',
      parentId: 'domain-1',
      childIds: ['concept-3', 'concept-4'],
      createdAt: 1700000002000,
      updatedAt: 1700000002000,
    },
    'topic-3': {
      id: 'topic-3',
      label: 'Data Communication',
      description: 'Presenting and visualizing data for different audiences.',
      type: 'topic',
      parentId: 'domain-1',
      childIds: ['concept-5'],
      createdAt: 1700000003000,
      updatedAt: 1700000003000,
    },
    'concept-1': {
      id: 'concept-1',
      label: 'Sampling',
      description: 'Selecting a subset of individuals from a population.',
      examples: ['Random sampling', 'Stratified sampling', 'Convenience sampling'],
      type: 'concept',
      parentId: 'topic-1',
      childIds: ['skill-1', 'skill-2'],
      createdAt: 1700000004000,
      updatedAt: 1700000004000,
    },
    'concept-2': {
      id: 'concept-2',
      label: 'Survey Design',
      description: 'Constructing effective questions and response formats.',
      type: 'concept',
      parentId: 'topic-1',
      childIds: [],
      createdAt: 1700000005000,
      updatedAt: 1700000005000,
    },
    'concept-3': {
      id: 'concept-3',
      label: 'Descriptive Statistics',
      description: 'Summarizing and describing features of a dataset.',
      examples: ['Mean', 'Median', 'Standard deviation'],
      type: 'concept',
      parentId: 'topic-2',
      childIds: [],
      createdAt: 1700000006000,
      updatedAt: 1700000006000,
    },
    'concept-4': {
      id: 'concept-4',
      label: 'Correlation vs Causation',
      description: 'Understanding the difference between association and causal relationship.',
      type: 'concept',
      parentId: 'topic-2',
      childIds: [],
      createdAt: 1700000007000,
      updatedAt: 1700000007000,
    },
    'concept-5': {
      id: 'concept-5',
      label: 'Data Visualization',
      description: 'Encoding data into visual forms to reveal patterns.',
      type: 'concept',
      parentId: 'topic-3',
      childIds: ['skill-3'],
      createdAt: 1700000008000,
      updatedAt: 1700000008000,
    },
    'skill-1': {
      id: 'skill-1',
      label: 'Calculate sample size',
      type: 'skill',
      parentId: 'concept-1',
      childIds: [],
      createdAt: 1700000009000,
      updatedAt: 1700000009000,
    },
    'skill-2': {
      id: 'skill-2',
      label: 'Identify sampling bias',
      type: 'skill',
      parentId: 'concept-1',
      childIds: [],
      createdAt: 1700000010000,
      updatedAt: 1700000010000,
    },
    'skill-3': {
      id: 'skill-3',
      label: 'Choose appropriate chart type',
      type: 'skill',
      parentId: 'concept-5',
      childIds: [],
      createdAt: 1700000011000,
      updatedAt: 1700000011000,
    },
  },
};
